### ISSUE TITLE
Add skipping paths option to `path`

### ISSUE THREAD

**Issue by thealmightygrant** [buildkite-plugins/monorepo-diff-buildkite-plugin#20]
Hi y'all, it's exciting that you took over this project! 🎉 

Is there any chance that you could implement [this feature](https://github.com/adikari/monorepo-diff-buildkite-plugin/pull/88#issuecomment-1308047128) in the future?

**Comment by chrismacnaughton-lambda** [comment]
I just want to add another vote for this feature!

**Comment by macjustice** [comment]
Sure would be nice. This feature is table stakes in other CI products.

**Comment by jamietanna** [comment]
I've raised:

- https://github.com/buildkite-plugins/monorepo-diff-buildkite-plugin/pull/27 (`git cherry-pick` of proposed change https://github.com/adikari/monorepo-diff-buildkite-plugin/pull/88 from the original repo)
- https://github.com/buildkite-plugins/monorepo-diff-buildkite-plugin/pull/28 (`git cherry-pick` of https://github.com/redpanda-data/monorepo-diff-buildkite-plugin/pull/1)

**Comment by jamietanna** [comment]
An alternate option I'd consider would be useful would be to have an `else`, i.e. so you can do:

```yaml
        watch:
          - path: "**/*.md"
            config:
              command: "..."
          - path: ".github/CODEOWNERS"
            config:
              command: "..."
          # otherwise run full E2E tests
          - else:
            config:
              command: "..." 
```
