### ISSUE TITLE
ECR Authentication Issues

### ISSUE THREAD

**Issue by mwwolters** [buildkite-plugins/monorepo-diff-buildkite-plugin#21]
I am trying to use this plugin in conjunction with the ecr plugin, but when I do I get a `no basic auth credentials` error when trying to push the container. The ECR login succeeded before the monorepo step ran:
```
[2024-07-10T22:47:38Z] ^^^ Authenticating with AWS ECR in <REDACTED> for <REDACTED> :ecr: :docker:
| [2024-07-10T22:47:39Z] WARNING! Your password will be stored unencrypted in <REDACTED>
| [2024-07-10T22:47:39Z] Configure a credential helper to remove this warning. See
| [2024-07-10T22:47:39Z] https://docs.docker.com/engine/reference/commandline/login/#credentials-store
| [2024-07-10T22:47:39Z]
| [2024-07-10T22:47:39Z] Login Succeeded
```

but it was unable to push. If I remove the monorepo plugin, then the push works as expected.

Working pipeline:
```
steps:
  - label: "Build"
    key: "key"
    commands:
      - cd ops
      - docker build . -f . -t $ECR_URI
      - docker push $ECR_URI
    plugins:
      - ecr#89b335a:
          login: true
          region: ${REGION}
          account-ids:
            - ${ECR_ACCOUNT}
```

Not working:
```
steps:
  - label: "Build"
    key: "key"
    plugins:
      - ecr#89b335a:
          login: true
          region: ${REGION}
          account-ids:
            - ${ECR_ACCOUNT}
      - monorepo-diff#v1.0.1:
          watch:
            - path: .
              config:
                commands:
                  - cd ops
                  - docker build . -f . -t $ECR_URI
                  - docker push $ECR_URI

```

**Comment by toote** [comment]
The issue here is that the `ecr` plugin is part of the step running the diff. This plugin uploads new steps to run and they will not have  the ECR plugin associated with them. Your piepline is equivalent to:

```
steps:
  - label: "Build"
    key: "key"
    command: "what the plugin does internally"
    plugins:
      - ecr#89b335a:
          login: true
          region: ${REGION}
          account-ids:
            - ${ECR_ACCOUNT}
  - label: "Uploaded by the plugin"
    command:
      - cd ops
      - docker build . -f . -t $ECR_URI
      - docker push $ECR_URI
```

Unfortunately, the plugin does not have support for plugins in the steps it uploads at this time. In the meantime, there are two workarounds:
1- creating a new YAML file in your repository with the steps as they are supposed to be run and have the `config` do a `buildkite-agent pipeline upload FILE.YAML` (which means that you will have access to the whole power of step configurations)
2- creating a new pipeline with your steps and changing the plugin's configuration to trigger that pipeline instead

**Comment by toote** [comment]
Now that #50 is merged, this scenario should be covered with the following pipeline configuration:

```yaml
steps:
  - label: "Build"
    key: "key"
      - monorepo-diff#v1.0.1:
          watch:
            - path: .
              config:
                plugins:
                  - ecr#89b335a:
                      login: true
                      region: ${REGION}
                      account-ids:
                        - ${ECR_ACCOUNT}
                commands:
                  - cd ops
                  - docker build . -f . -t $ECR_URI
                  - docker push $ECR_URI
```
