### ISSUE TITLE
Allow for "default" config to run if no path match

### ISSUE THREAD

**Issue by fivetran-joseolmo** [buildkite-plugins/monorepo-diff-buildkite-plugin#23]
Hi!
Would it be possible to have a “default” build for when no path matched the watched folders?
So, basically, we’d like to have a pipeline definition like this:
```
steps:
  - key: tests-pipeline
    label: ":pipeline:"
    plugins:
      - monorepo-diff#v1.0.1:
          watch:
            - path: folder_a/**
              config:
                command: buildkite-agent pipeline upload a_tests.yml
            - path: folder_b/**
              config:
                command: buildkite-agent pipeline upload b_tests.yml
            - default:
              config:
                command: buildkite-agent pipeline upload other_tests.yml
```
We want `other_tests` to run if the changes happen on any folder other than `folder_a` or `folder_b`
Also, like the current functionality on the plugin, if change happens on all three "paths" we would like all three pipelines to run.
We could accomplish this with glob exclude patterns but they do not seem to work at the moment according to this issue: https://github.com/adikari/monorepo-diff-buildkite-plugin/issues/95

**Comment by jamietanna** [comment]
This would probably cover the suggestion raised in https://github.com/buildkite-plugins/monorepo-diff-buildkite-plugin/issues/20#issuecomment-2396413641 (aka `else`) quite nicely

**Comment by tomowatt** [comment]
Hey @fivetran-joseolmo 
With the release of [v1.1.0](https://github.com/buildkite-plugins/monorepo-diff-buildkite-plugin/releases/tag/v1.1.0) which includes the support for a "default" config, wanted to check if this resolves this issue and the request?

**Comment by fivetran-joseolmo** [comment]
Thanks for the ping @tomowatt.
I'm testing the new version and it does not seem to work for me, maybe I'm doing something wrong. I have this pipeline:
```
steps:
  - key: dynamic-test-pipeline
    label: ":fork: build pipeline based on diff changes"
    agents:
      queue: "default"
    plugins:
      - monorepo-diff#v1.1.0:
          log_level: "debug"
          interpolation: false
          diff: .buildkite/scripts/monorepo/diff-against-branch-point.sh
          watch:
            - path:
                - .buildkite/**
              config:
                label: ":buildkite:"
                command: echo ".buildkite changed"
            - path:
                - monorepo-test
              config:
                label: ":test_tube:"
                command: echo "monorepo-test changed"
            - default:
                config:
                  label: ":white_check_mark:"
                  command: echo "default triggered"
```
I have two folders, `monorepo-tests` and `monorepo-tests-2`, so I expected the `default` section to trigger for the `monorepo-tests-2` but it doesn't.
Buildkite logs:
```
  | 2024-11-01 10:52:08 CEST | Running plugin monorepo-diff command hook | 6s
  | 2024-11-01 10:52:08 CEST | $ /buildkite/plugins/buildkite-agent-k8s-default-rv846-p5zpw-1/github-com-buildkite-plugins-monorepo-diff-buildkite-plugin-v1-1-0/hooks/command
  | 2024-11-01 10:52:08 CEST | INFO[0000] --- running monorepo-diff-buildkite-plugin 1.1.0
  | 2024-11-01 10:52:08 CEST | INFO[2024-11-01T09:52:08Z] Running diff command: .buildkite/scripts/monorepo/diff-against-branch-point.sh
  | 2024-11-01 10:52:13 CEST | DEBU[2024-11-01T09:52:13Z] Output from diff:
  | 2024-11-01 10:52:13 CEST | .buildkite/tests.yml
  | 2024-11-01 10:52:13 CEST | monorepo-test-2/README.md
  | 2024-11-01 10:52:13 CEST | monorepo-test/README.md
  | 2024-11-01 10:52:13 CEST | Generated Pipeline:
  | 2024-11-01 10:52:13 CEST | steps:
  | 2024-11-01 10:52:13 CEST | - label: ':buildkite:'
  | 2024-11-01 10:52:13 CEST | command: echo ".buildkite changed"
  | 2024-11-01 10:52:13 CEST | - label: ':test_tube:'
  | 2024-11-01 10:52:13 CEST | command: echo "monorepo-test changed"
```
Let me know if you need more info to debug
