### ISSUE TITLE
Only execute trigger once for multiple paths

### ISSUE THREAD

**Issue by prichmond-q** [buildkite-plugins/monorepo-diff-buildkite-plugin#24]
### Current behaviour
I have a setup that is very similar to the sample below. 

If either `app/` or `app/bin/service` are changed, it will trigger the `data-genrator` build. But, if files are changed matching both paths, it will trigger 2 builds. 

### Expected behaviour

As per the documentation, it states;
 
> If the changes are made to either app/ or app/bin/service/ it triggers the pipeline data-generator

I read this as it should only trigger the build once if either of those paths were changed, but maybe I misinterpreted it. If so, is there a way to only trigger the build once if multiple paths are changed for the same trigger?  

**Sample pipeline file with multiple paths**
```
steps:
  - label: "Triggering pipelines with plugin"
    plugins:
      - monorepo-diff#v1.0.1:
          watch:
            - path: test/.buildkite/
              config: # Required [trigger step configuration]
                trigger: test-pipeline # Required [trigger pipeline slug]
            - path:
                - app/
                - app/bin/service/
              config:
                trigger: "data-generator"
```
