### ISSUE TITLE
Support multiple steps when matching a `path`

### ISSUE THREAD

**Issue by jamietanna** [buildkite-plugins/monorepo-diff-buildkite-plugin#30]
Right now, the `monorepo-diff` plugin only makes it possible to perform a single step when matching a given `path`.

For instance, let's take the following snippet:

```yaml
# .buildkite/pipeline.yml
steps:
  - label: "Triggering pipelines"
    plugins:
      - monorepo-diff#v1.0.1:
          diff: "git diff --name-only HEAD~1"
          watch:
            # ...
            - path: test/bin/
              config:
                command: "echo Make Changes to Bin"
                # alternatively `commands` for a multi-line, but still single-step build
            # ...
```

We can see that we can only run one `command`/one set of `commands` here, which means we can't perform a multi-step build.

Therefore what we find is that we need to produce a separate pipeline for this, and make the following changes:

```diff
# .buildkite/pipeline.yml
steps:
  - label: "Triggering pipelines"
    plugins:
      - monorepo-diff#v1.0.1:
          diff: "git diff --name-only HEAD~1"
          watch:
			# ...
            - path: test/bin/
              config:
-               command: "echo Make Changes to Bin"
+               label: ":pipeline: Upload Pipeline for Bin"
+               command: "buildkite-agent pipeline upload .buildkite/test-bin.yml"
			# ...
```

Then we would have the following separate pipeline file:

```yaml
# .buildkite/test-bin.yml
steps:
  - label: "Do something"
    commands:
    - echo "..."
  - label: "Do something else"
    commands:
    - echo "..."
  # ...
```

This may be intentional, as a way to ensure that pipelines in the monolithic pipeline build is simplified, but sometimes it can be useful to set up a multi-step pipeline without the overhead of a new file that needs to be managed.

It'd be good to understand if it's intentional - if so we can tweak the docs - or if not, it'd be appreciated if we could instead provide multiple steps.
