### ISSUE TITLE
Triggered build missing env/meta_data blocks

### ISSUE THREAD

**Issue by nolan-fw** [buildkite-plugins/monorepo-diff-buildkite-plugin#32]
I'm struggling trying to pass inputs to my triggered pipeline.

```
steps:
  - label: ":pipeline: Starting pipelines"
    plugins:
      monorepo-diff#v1.0.1:
        diff: ".buildkite/scripts/diff"
        watch:
          - path: "subfolder/"
            config:
              label: ":pipeline: Trigger external"
              trigger: external-build
              build:
                branch: "feat/external-build"
                commit: "HEAD"
                meta_data:
                  current-branch: "${BUILDKITE_BRANCH}"
                env:
                  CURRENT_BRANCH="${BUILDKITE_BRANCH}"
                message: "[${BUILDKITE_BRANCH}] ${BUILDKITE_MESSAGE} Trigger"
```

The output from this running is missing the meta_data and env blocks, and the triggered build is failing on it:
```
INFO[2024-10-15T19:34:23Z] Running diff command: .buildkite/scripts/diff
Generated Pipeline:
steps:
- trigger: external-build
  label: ':pipeline: Trigger external'
  build:
    message: '[feat/triggering-build] Test Trigger'
    branch: feat/external-build
    commit: HEAD
```

Have I misunderstood something in the config block?
