### ISSUE TITLE
`default` config doesn't work when there's a `wait: true`

### ISSUE THREAD

**Issue by jamietanna** [buildkite-plugins/monorepo-diff-buildkite-plugin#34]
When using the new `default` configuration released as part of #20 / #29, it appears that this does not work in conjunction with the `wait: true`

For the following Buildkite configuration:

```yaml
steps:
  - label: "Triggering pipelines"
    plugins:
      monorepo-diff#v1.1.0:
        diff: ".buildkite/diff ${BUILDKITE_COMMIT}"
        wait: true
        watch:
          - path: "renovate.json"
            config:
              label: "Verify Renovate configuration"
              command: "renovate-config-validator"
              agents:
                # ...

          # ... otherwise, fall back to the default pipeline
          - default:
              config:
                label: ":pipeline: Upload default Pipeline"
                command: "buildkite-agent pipeline upload .buildkite/default-pipeline.yml"
```

This then fails to run:

```
$ /buildkite-agent/plugins/.../github-com-buildkite-plugins-monorepo-diff-buildkite-plugin-v1-1-0/hooks/command
INFO[0000] --- running monorepo-diff-buildkite-plugin 1.1.0
INFO[2024-10-23T08:45:46Z] Running diff command: .buildkite/diff d5e161b1e7c95f41861f0c84b73d5097175a5328
Generated Pipeline:
steps:
- {}
- wait: null
FATA[2024-10-23T08:45:48Z] +++ failed to upload pipeline: command `buildkite-agent` failed: exit status 1
🚨 Error: The command exited with status 1
user command error: The plugin monorepo-diff command hook exited with status 1
```

**Comment by toote** [comment]
Apparently, this is an issue with the documentation: the `default` key does not actually support a whole `config` inside of it.

The following should work just fine:

```yaml
steps:
  - label: "Triggering pipelines"
    plugins:
      monorepo-diff#v1.1.0:
        diff: ".buildkite/diff ${BUILDKITE_COMMIT}"
        wait: true
        watch:
          - path: "renovate.json"
            config:
              label: "Verify Renovate configuration"
              command: "renovate-config-validator"
              agents:
                # ...

          # ... otherwise, fall back to the default pipeline
          - default:
              label: ":pipeline: Upload default Pipeline"
              command: "buildkite-agent pipeline upload .buildkite/default-pipeline.yml"
```

Working on a PR to correct that (with proper tests)

**Comment by jamietanna** [comment]
Thank you! I can confirm, that with the following change:

```diff
diff --git .buildkite/pipeline.yml .buildkite/pipeline.yml
index f95818e..91e2554 100644
--- .buildkite/pipeline.yml
+++ .buildkite/pipeline.yml
@@ -3,7 +3,7 @@
 steps:
   - label: "Triggering pipelines"
     plugins:
-      monorepo-diff#v1.1.0:
+      monorepo-diff#c96be5d9e75642e991e86e455616cea08436d497:
         diff: ".buildkite/diff ${BUILDKITE_COMMIT}"
         wait: true
         watch:
@@ -17,6 +17,5 @@ steps:
                 image: "..."
           # ... otherwise, fall back to the default pipeline
           - default:
-              config:
-                label: ":pipeline: Upload default Pipeline"
-                command: "buildkite-agent pipeline upload .buildkite/default-pipeline.yml"
+              label: ":pipeline: Upload default Pipeline"
+              command: "buildkite-agent pipeline upload .buildkite/default-pipeline.yml"
```

I can now correctly see the `default` step working :clap: This looks good to release

**Comment by toote** [comment]
@jamietanna actually, what I mentioned was that not using the `config` element should have worked. My PR actually implements the support so that your original configuration works the same as the one you modified. In any case, the release is already done so either way should work with v1.2.0

**Comment by jamietanna** [comment]
Oh sorry, I stand corrected!

I think what I'd done wrong was that the `config` was _nested_ in the `default` example I'd been using:

```yaml
          - path: "renovate.json"
            # 👇🏼 note that this is at the same level as `path`
            config:
              label: "Verify Renovate configuration"

          # ... otherwise, fall back to the default pipeline
          - default:
              # 👇🏼 note that this is nested under `default`, which is wrong ⚠️ ⚠️
              config:
                label: ":pipeline: Upload default Pipeline"
                command: "buildkite-agent pipeline upload .buildkite/default-pipeline.yml"
```

Thanks for the correction!
