### ISSUE TITLE
Watch paths only work for directories, but not for exact match on single files or file wildcards

### ISSUE THREAD

**Issue by c2h5oh** [buildkite-plugins/monorepo-diff-buildkite-plugin#42]
```
$ git diff --name-only HEAD~1
configs/dev.yaml
```

```yaml
steps:
    plugins:
      - monorepo-diff#v1.2.0:
          watch:
            - path: configs/dev.yaml
              config:
                command: echo "dev config changed - exact match"

            - path: configs/dev.*
              config:
                command: echo "dev config changed - wildcard match"

            - path: configs/
              config:
                command: echo "a config changed - whole directory match"
```

first two matches are ignored, only 3rd one triggers.
