### ISSUE TITLE
[Feature request] Add branch pattern support in case command is used

### ISSUE THREAD

**Issue by kwozn-softserve** [buildkite-plugins/monorepo-diff-buildkite-plugin#51]
When I configure the plugin to run a command, branches pattern is ignored.
```
- monorepo-diff#v1.3.0:
    watch:
      - path:
        - whatever.txt
        config:
          label: "Dummy label"
          branches: "master"
          command: |
            echo "I'm running on branch $BUILDKITE_BRANCH"
```

Current behaviour: command is executed.

<img width="1713" alt="Image" src="https://github.com/user-attachments/assets/9415606b-8ca2-4bfa-abe2-12eb031a090f" />

Expected behaviour: command is not executed.
