### ISSUE TITLE
Support for plugins

### ISSUE THREAD

**Issue by jasonwbarnett** [buildkite-plugins/monorepo-diff-buildkite-plugin#79]
I couldn't tell if it's undocumented or unsupported.

For really simple steps it would be nice to run plugins alongside them. For example, if I'm adding a step that requires CodeArtifact authentication, it would be nice to use a plugin to provide that.

Example of what I'd like to see support for:

```yaml
steps:
  - label: "Trigger steps and pipelines conditionally"
    plugins:
      - monorepo-diff#v1.3.0:
          watch:
            - path:
                - "src/python/**/*.py"
              config:
                label: "Verify OpenAPI Schema and Generated Python Client"
                agents:
                  queue: linux-amd64-8x32
                command: |
                  set -euo pipefail

                  echo "--- Generating Python Client"
                  cd src/python
                  task generate-python-client

                  if ! git diff --quiet; then
                    echo "+++ ❌ Uncommitted changes detected:"
                    git diff
                    echo "+++ To fix: Run the following locally, commit the changes, and push your branch:"
                    echo "    task generate-python-client"
                    exit 1
                  fi
                plugins:
                  - ".buildkite/plugins/code-artifact-login":
                      domain: "<domain>"
                      region: "us-east-1"
                      account-id: "<account-id>"
                      repository: "<repo>"
```
