### ISSUE TITLE
command step does not support `env` key

### ISSUE THREAD

**Issue by valkum** [buildkite-plugins/monorepo-diff-buildkite-plugin#82]
The comment step does not support the `env` key. If an `env` key is present, the generated pipeline uses `rawEnv` as the key leading to pipeline upload errors.

A current workaround is to use inline ENV vars

```
- command: APP_ENV=prod buildkite-agent pipline upload whatever.yml
```

It would be nice if the plugin would support more default keys. 

Related: https://github.com/buildkite-plugins/monorepo-diff-buildkite-plugin/issues/78

**Comment by valkum** [comment]
Looking at https://github.com/buildkite-plugins/monorepo-diff-buildkite-plugin/blob/master/plugin.go#L349 it should be supported. This might be caused by the plugin accepting an invalid group step config and doing invalid things as a result.

E.g. we had
```
plugins:
- monorepo-diff#v1.4.0:
    diff: ".buildkite/scripts/git-diff.sh main ${BUILDKITE_COMMIT}"
    watch:
      - path:
          - "other-path/**"
        config:
          steps:
            - command: do-something
               env: 
                 - TEST: true
```
The config is wrong in this case, as steps suggests this is a group step but it is missing the required `group` or `label` key.

Closing this for now. #83 should cover the case of invalid `config` values.
