### ISSUE TITLE
pipeline upload failure if no steps are configured

### ISSUE THREAD

**Issue by valkum** [buildkite-plugins/monorepo-diff-buildkite-plugin#83]
If you have a watched path without any configured steps 

```
plugins:
- monorepo-diff#v1.4.0:
    diff: ".buildkite/scripts/git-diff.sh main ${BUILDKITE_COMMIT}"
    watch:
      - path:
          - "some-oath/**"
        config:
          steps:
      - path:
          - "other-path/**"
        config:
          steps:
            - command: do-something
```
there is no error thrown that is helpful.
Instead, the plugin creates a pipeline that fails to upload. The pipeline looks like this:

```
Generated Pipeline:
steps:
    - {}
```

The resulting error is
```
FATA[2025-06-30T04:33:20-07:00] +++ failed to upload pipeline: command `buildkite-agent` failed: exit status 1
```
